baseurl = "https://geek.cl/" # Controls base URL
languageCode = "es" # Controls site language
title = "geek" # Homepage title and page title suffix
paginate = 10 # Number of posts to show before paginating

theme = "after-dark" # Set default theme

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "UA-2992879-17" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = "Blog geek" # Suggested, controls default description meta
  author = "Arturo C." # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  powered_by = true # Optional, set false to disable credits
  images = [
    "https://source.unsplash.com/category/technology/2000x1322"
  ] # Suggested, controls default Open Graph images
  theme_variant = "" # Optional, for use to overriding default theme

[permalinks]
  post = "/:slug/"
  pagina = "/pagina/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"

[blackfriday]
  hrefTargetBlank = true

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
